name: PUBLISH
on:
  push:
    branches: ['app-release']


jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        poetry-version: ["1.2.2", "1.7.1"]
        os: [ubuntu-22.04, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
          - name: Python Poetry Action
            uses: abatilo/actions-poetry@v3.0.0
          - name: Publish app
            run: poetry --help     

