name: PUBLISH
on:
  push:
    branches: ['app-release']


jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.7.1"]
        os: [windows-latest] #, ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v3.0.0
      - name: Install dependencies
        run: poetry lock &&  poetry install
      - name: Publish CLI tool
        run: poetry run build

